(()=>{'use strict';
const KEY='mkg-cv-builder-v1';
const steps=[['personal','Personal details','Start with the essentials employers need to contact you.'],['profile','Professional profile','Write a short introduction that explains the value you bring.'],['work','Work history','Add your most relevant roles and focus on results, responsibilities and impact.'],['skills','Skills','Add the strengths and practical skills most relevant to the jobs you want.'],['education','Education','Add qualifications, courses and formal education.'],['certificates','Certificates & licences','Include professional certificates, licences and accreditations.'],['projects','Projects & achievements','Show notable projects, awards or achievements that strengthen your application.']];
const blank=()=>({personal:{name:'',title:'',email:'',phone:'',location:'',linkedin:'',website:''},profile:'',writingHelp:'suggest',writingStyle:'professional',work:[{role:'',company:'',location:'',start:'',end:'',bullets:''}],skills:'',education:[{qualification:'',institution:'',location:'',start:'',end:'',details:''}],certificates:[{name:'',issuer:'',date:'',expiry:''}],projects:[{name:'',subtitle:'',date:'',details:''}]});
let s=load(),step=0,timer;const $=id=>document.getElementById(id),content=$('stepContent'),preview=$('cvPreview'),pane=$('previewPane');
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));const base=blank();return saved?{...base,...saved,personal:{...base.personal,...(saved.personal||{})},work:arr(saved.work,base.work),education:arr(saved.education,base.education),certificates:arr(saved.certificates,base.certificates),projects:arr(saved.projects,base.projects)}:base}catch{return blank()}}
const arr=(a,b)=>Array.isArray(a)&&a.length?a:b;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(msg=false){localStorage.setItem(KEY,JSON.stringify(s));$('saveStatus').textContent='Saved locally';if(msg)toast('CV saved on this device')}
function autosave(){$('saveStatus').textContent='Saving…';clearTimeout(timer);timer=setTimeout(()=>save(),250)}function changed(){autosave();drawPreview()}
function nav(){const box=$('stepList');box.innerHTML=steps.map((x,i)=>`<button class="step-button ${i===step?'active':''}" type="button" data-step="${i}"><span class="step-number">${i+1}</span><span class="step-label">${esc(x[1])}</span></button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>go(+b.dataset.step))}
function go(i){if(i<0||i>=steps.length)return;step=i;drawStep();document.querySelector('.editor-pane')?.scrollTo?.({top:0,behavior:'smooth'})}
function drawStep(){const [id,title,intro]=steps[step];$('stepEyebrow').textContent=`Step ${step+1} of ${steps.length}`;$('stepTitle').textContent=title;$('stepIntro').textContent=intro;$('progressText').textContent=`${step+1} of ${steps.length}`;$('progressBar').style.width=((step+1)/steps.length*100)+'%';$('backBtn').disabled=step===0;$('nextBtn').textContent=step===steps.length-1?'Finish':'Next';content.innerHTML=forms[id]();bind();nav()}
const input=(label,key,val,ph='',full='')=>`<div class="field ${full}"><label>${label}</label><input data-personal="${key}" value="${esc(val)}" placeholder="${esc(ph)}"></div>`;
const repInput=(label,g,i,k,val,ph='')=>`<div class="field"><label>${label}</label><input data-repeat="${g}" data-i="${i}" data-k="${k}" value="${esc(val)}" placeholder="${esc(ph)}"></div>`;
const cardHead=(t,g,i,len)=>`<div class="repeat-card-header"><strong>${t}</strong><div class="repeat-actions"><button class="small-btn" type="button" data-move="up" data-g="${g}" data-i="${i}" ${i===0?'disabled':''}>↑</button><button class="small-btn" type="button" data-move="down" data-g="${g}" data-i="${i}" ${i===len-1?'disabled':''}>↓</button><button class="small-btn remove" type="button" data-remove="${g}" data-i="${i}">×</button></div></div>`;
const forms={
personal(){const p=s.personal;return `<div class="section-help"><strong>Keep it professional.</strong> You do not need age, marital status or a photo for a standard UK CV.</div><div class="form-grid">${input('Full name','name',p.name,'Alex Morgan')}${input('Professional title','title',p.title,'Project Coordinator')}${input('Email','email',p.email,'alex@example.com')}${input('Phone','phone',p.phone,'07123 456789')}${input('Location','location',p.location,'London, UK')}${input('LinkedIn','linkedin',p.linkedin,'linkedin.com/in/alexmorgan')}${input('Website / portfolio','website',p.website,'alexmorgan.co.uk','full')}</div>`},
profile(){return `<div class="section-help"><strong>Strong profile formula:</strong> who you are + your strongest experience + the value you offer.</div><div class="form-grid"><div class="field"><label>Writing help preference</label><select data-simple="writingHelp"><option value="suggest">Suggest polished wording</option><option value="rewrite">Rewrite my rough notes</option><option value="bullets">Create bullet points from job titles</option><option value="manual">I will write it myself</option></select><span class="hint">Saved now; AI wording actions are planned for a later stage.</span></div><div class="field"><label>Wording style</label><select data-simple="writingStyle"><option value="professional">Professional and balanced</option><option value="concise">Concise and direct</option><option value="achievement">Achievement-focused</option><option value="friendly">Warm and approachable</option></select></div><div class="field full"><label>Professional profile</label><textarea data-simple="profile" maxlength="650" placeholder="Experienced operations professional with a strong record of coordinating teams...">${esc(s.profile)}</textarea><div class="char-count">${s.profile.length}/650</div></div></div>`},
work(){return repeatIntro('Make each role evidence-led. Put the newest role first.',s.work.map((x,i)=>`<div class="repeat-card">${cardHead('Role '+(i+1),'work',i,s.work.length)}<div class="form-grid">${repInput('Job title','work',i,'role',x.role,'Operations Coordinator')}${repInput('Employer','work',i,'company',x.company,'Example Company')}${repInput('Location','work',i,'location',x.location,'London')}${repInput('Start date','work',i,'start',x.start,'Jan 2023')}${repInput('End date','work',i,'end',x.end,'Present')}<div class="field full"><label>Highlights</label><textarea class="compact" data-repeat="work" data-i="${i}" data-k="bullets" placeholder="Led a team of...&#10;Reduced processing time by...">${esc(x.bullets)}</textarea><span class="hint">Use a new line for each bullet point.</span></div></div></div>`).join(''),'work','+ Add another role')},
skills(){return `<div class="section-help"><strong>Prioritise relevance.</strong> Add practical, technical and people skills.</div><div class="field"><label>Skills</label><textarea data-simple="skills" placeholder="Project coordination&#10;Stakeholder management&#10;Microsoft 365">${esc(s.skills)}</textarea><span class="hint">Enter one skill per line. Commas also work.</span></div>`},
education(){return repeatIntro('Keep education concise. Include qualification, institution and dates.',s.education.map((x,i)=>`<div class="repeat-card">${cardHead('Education '+(i+1),'education',i,s.education.length)}<div class="form-grid">${repInput('Qualification','education',i,'qualification',x.qualification,'BSc Business Management')}${repInput('Institution','education',i,'institution',x.institution,'Example University')}${repInput('Location','education',i,'location',x.location,'London')}${repInput('Start date','education',i,'start',x.start,'Sep 2018')}${repInput('End date','education',i,'end',x.end,'Jun 2021')}<div class="field full"><label>Details</label><textarea class="compact" data-repeat="education" data-i="${i}" data-k="details">${esc(x.details)}</textarea></div></div></div>`).join(''),'education','+ Add education')},
certificates(){return repeatIntro('Include active, relevant credentials first.',s.certificates.map((x,i)=>`<div class="repeat-card">${cardHead('Credential '+(i+1),'certificates',i,s.certificates.length)}<div class="form-grid">${repInput('Certificate / licence','certificates',i,'name',x.name,'PRINCE2 Foundation')}${repInput('Issuer','certificates',i,'issuer',x.issuer,'PeopleCert')}${repInput('Awarded','certificates',i,'date',x.date,'Mar 2025')}${repInput('Expiry','certificates',i,'expiry',x.expiry,'Mar 2028')}</div></div>`).join(''),'certificates','+ Add certificate or licence')},
projects(){return repeatIntro('Add projects, awards, improvements or achievements.',s.projects.map((x,i)=>`<div class="repeat-card">${cardHead('Item '+(i+1),'projects',i,s.projects.length)}<div class="form-grid">${repInput('Project / achievement','projects',i,'name',x.name,'Warehouse process redesign')}${repInput('Organisation / context','projects',i,'subtitle',x.subtitle,'Example Company')}${repInput('Date','projects',i,'date',x.date,'2026')}<div></div><div class="field full"><label>What you achieved</label><textarea class="compact" data-repeat="projects" data-i="${i}" data-k="details">${esc(x.details)}</textarea></div></div></div>`).join(''),'projects','+ Add project or achievement')}
};
function repeatIntro(t,html,g,btn){return `<div class="section-help"><strong>Tip.</strong> ${t}</div><div class="repeat-list">${html}</div><button class="btn btn-secondary add-btn" type="button" data-add="${g}">${btn}</button>`}
function bind(){content.querySelectorAll('[data-personal]').forEach(e=>e.oninput=()=>{s.personal[e.dataset.personal]=e.value;changed()});content.querySelectorAll('[data-simple]').forEach(e=>{e.value=s[e.dataset.simple]||e.value;e.oninput=e.onchange=()=>{s[e.dataset.simple]=e.value;changed();drawStep()}});content.querySelectorAll('[data-repeat]').forEach(e=>e.oninput=()=>{s[e.dataset.repeat][+e.dataset.i][e.dataset.k]=e.value;changed()});content.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));content.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove,+b.dataset.i));content.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>move(b.dataset.g,+b.dataset.i,b.dataset.move))}
function add(g){const t={work:{role:'',company:'',location:'',start:'',end:'',bullets:''},education:{qualification:'',institution:'',location:'',start:'',end:'',details:''},certificates:{name:'',issuer:'',date:'',expiry:''},projects:{name:'',subtitle:'',date:'',details:''}};s[g].push({...t[g]});changed();drawStep()}
function remove(g,i){if(s[g].length===1){Object.keys(s[g][0]).forEach(k=>s[g][0][k]='')}else s[g].splice(i,1);changed();drawStep()}
function move(g,i,d){const j=d==='up'?i-1:i+1;if(j<0||j>=s[g].length)return;[s[g][i],s[g][j]]=[s[g][j],s[g][i]];changed();drawStep()}
const lines=v=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean);const any=(o,ks)=>ks.some(k=>String(o[k]||'').trim());const dates=(a,b)=>[a,b].filter(Boolean).join(' – ');
function sec(t,h){return `<section class="cv-section"><h2 class="cv-section-title">${t}</h2>${h}</section>`}
function drawPreview(){const p=s.personal,contact=[p.email,p.phone,p.location,p.linkedin,p.website].filter(Boolean);const work=s.work.filter(x=>any(x,['role','company','bullets'])),edu=s.education.filter(x=>any(x,['qualification','institution','details'])),cert=s.certificates.filter(x=>any(x,['name','issuer'])),proj=s.projects.filter(x=>any(x,['name','subtitle','details'])),skills=lines(s.skills);preview.innerHTML=`<header class="cv-head"><h1 class="cv-name">${esc(p.name||'Your Name')}</h1><p class="cv-title">${esc(p.title||'Professional Title')}</p><div class="cv-contact">${contact.length?contact.map(c=>`<span>${esc(c)}</span>`).join(''):'<span class="cv-placeholder">email · phone · location · LinkedIn</span>'}</div></header>${sec('Professional profile',s.profile?`<p>${esc(s.profile)}</p>`:'<p class="cv-placeholder">Your professional profile will appear here.</p>')}${sec('Work experience',work.length?work.map(x=>entry(x.role||'Job title',[x.company,x.location].filter(Boolean).join(' · '),dates(x.start,x.end),lines(x.bullets))).join(''):'<p class="cv-placeholder">Your work history will appear here.</p>')}${sec('Skills',skills.length?`<div class="cv-skills">${skills.map(x=>`<span class="cv-skill">${esc(x)}</span>`).join('')}</div>`:'<p class="cv-placeholder">Your key skills will appear here.</p>')}${edu.length?sec('Education',edu.map(x=>entry(x.qualification||'Qualification',[x.institution,x.location].filter(Boolean).join(' · '),dates(x.start,x.end),[],x.details)).join('')):''}${cert.length?sec('Certificates & licences',cert.map(x=>entry(x.name||'Certificate',x.issuer,[x.date,x.expiry?`Expiry: ${x.expiry}`:''].filter(Boolean).join(' · '))).join('')):''}${proj.length?sec('Projects & achievements',proj.map(x=>entry(x.name||'Project or achievement',x.subtitle,x.date,[],x.details)).join('')):''}`}
function entry(title,sub,meta,bul=[],detail=''){return `<div class="cv-entry"><div class="cv-entry-head"><span class="cv-entry-title">${esc(title)}</span><span class="cv-entry-meta">${esc(meta)}</span></div>${sub?`<p class="cv-entry-sub">${esc(sub)}</p>`:''}${bul.length?`<ul>${bul.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>`:''}${detail?`<p class="cv-entry-detail">${esc(detail)}</p>`:''}</div>`}
function pdf(){save();toast('Opening print view — choose Save as PDF');setTimeout(()=>window.print(),120)}
function word(){save();const css='body{font-family:Arial,sans-serif;font-size:10pt;color:#242424}h1{color:#183b5b}.cv-head{border-bottom:2px solid #245b8f}.cv-section-title{color:#245b8f;text-transform:uppercase;font-size:9pt}.cv-placeholder{display:none}';const blob=new Blob(['\ufeff',`<!doctype html><html><head><meta charset="utf-8"><style>${css}</style></head><body>${preview.innerHTML}</body></html>`],{type:'application/msword;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=((s.personal.name||'My CV').replace(/[^a-z0-9\-_ ]/gi,'')||'My CV')+' - CV.doc';document.body.appendChild(a);a.click();a.remove();toast('Word-compatible CV downloaded')}
function toast(m){const x=$('toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
$('backBtn').onclick=()=>go(step-1);$('nextBtn').onclick=()=>step<steps.length-1?go(step+1):(save(true),pane.classList.add('open'),toast('CV ready to review and export'));$('saveBtn').onclick=()=>save(true);$('wordBtn').onclick=word;$('pdfBtn').onclick=pdf;$('mobilePreviewBtn').onclick=()=>pane.classList.add('open');$('closePreviewBtn').onclick=()=>pane.classList.remove('open');$('resetBtn').onclick=()=>$('resetDialog').showModal();$('confirmResetBtn').onclick=()=>{localStorage.removeItem(KEY);s=blank();step=0;drawStep();drawPreview();toast('CV cleared')};drawStep();drawPreview();})();
